export default [
  {
    login: "Programmer129",
    id: 23177448,
    node_id: "MDQ6VXNlcjIzMTc3NDQ4",
    avatar_url: "https://avatars0.githubusercontent.com/u/23177448?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Programmer129",
    html_url: "https://github.com/Programmer129",
    followers_url: "https://api.github.com/users/Programmer129/followers",
    following_url:
      "https://api.github.com/users/Programmer129/following{/other_user}",
    gists_url: "https://api.github.com/users/Programmer129/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Programmer129/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Programmer129/subscriptions",
    organizations_url: "https://api.github.com/users/Programmer129/orgs",
    repos_url: "https://api.github.com/users/Programmer129/repos",
    events_url: "https://api.github.com/users/Programmer129/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Programmer129/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "anakhas",
    id: 61705316,
    node_id: "MDQ6VXNlcjYxNzA1MzE2",
    avatar_url: "https://avatars1.githubusercontent.com/u/61705316?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/anakhas",
    html_url: "https://github.com/anakhas",
    followers_url: "https://api.github.com/users/anakhas/followers",
    following_url:
      "https://api.github.com/users/anakhas/following{/other_user}",
    gists_url: "https://api.github.com/users/anakhas/gists{/gist_id}",
    starred_url: "https://api.github.com/users/anakhas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/anakhas/subscriptions",
    organizations_url: "https://api.github.com/users/anakhas/orgs",
    repos_url: "https://api.github.com/users/anakhas/repos",
    events_url: "https://api.github.com/users/anakhas/events{/privacy}",
    received_events_url: "https://api.github.com/users/anakhas/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "avtojohn",
    id: 36630336,
    node_id: "MDQ6VXNlcjM2NjMwMzM2",
    avatar_url: "https://avatars2.githubusercontent.com/u/36630336?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/avtojohn",
    html_url: "https://github.com/avtojohn",
    followers_url: "https://api.github.com/users/avtojohn/followers",
    following_url:
      "https://api.github.com/users/avtojohn/following{/other_user}",
    gists_url: "https://api.github.com/users/avtojohn/gists{/gist_id}",
    starred_url: "https://api.github.com/users/avtojohn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/avtojohn/subscriptions",
    organizations_url: "https://api.github.com/users/avtojohn/orgs",
    repos_url: "https://api.github.com/users/avtojohn/repos",
    events_url: "https://api.github.com/users/avtojohn/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/avtojohn/received_events",
    type: "User",
    site_admin: false,
  },
];
