export default {
  login: "EasyBreezy97",
  id: 39771123,
  node_id: "MDQ6VXNlcjM5NzcxMTIz",
  avatar_url: "https://avatars0.githubusercontent.com/u/39771123?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/EasyBreezy97",
  html_url: "https://github.com/EasyBreezy97",
  followers_url: "https://api.github.com/users/EasyBreezy97/followers",
  following_url:
    "https://api.github.com/users/EasyBreezy97/following{/other_user}",
  gists_url: "https://api.github.com/users/EasyBreezy97/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/EasyBreezy97/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/EasyBreezy97/subscriptions",
  organizations_url: "https://api.github.com/users/EasyBreezy97/orgs",
  repos_url: "https://api.github.com/users/EasyBreezy97/repos",
  events_url: "https://api.github.com/users/EasyBreezy97/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/EasyBreezy97/received_events",
  type: "User",
  site_admin: false,
  name: "Guram",
  company: "@translatege ",
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 21,
  public_gists: 6,
  followers: 3,
  following: 9,
  created_at: "2018-05-30T14:48:42Z",
  updated_at: "2020-08-17T12:49:43Z",
};
